# Generated by Django 6.0.5 on 2026-10-06 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('iq', 'IQ Test'), ('math', 'Matematika'), ('english', 'Ingliz tili'), ('native', 'Ona tili va Adabiyot')], max_length=20, unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('description_uz', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='Brain', max_length=50)),
                ('color', models.CharField(blank=True, default='indigo', max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=2400)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Test kategoriyasi',
                'verbose_name_plural': 'Test kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('image_url', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('pattern', 'Pattern Recognition & Matrix'), ('spatial', 'Spatial Visualization'), ('numerical', 'Numerical Sequences'), ('abstract', 'Abstract Reasoning'), ('algebra', 'Algebra'), ('geometry', 'Geometry'), ('arithmetic', 'Arithmetic'), ('logic', 'Logic'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('ortography', 'Ortografiya'), ('literature', 'Adabiyot'), ('grammar_uz', 'Grammatika'), ('analysis', 'Tahlil')], max_length=30)),
                ('difficulty', models.FloatField(default=1.0)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.testcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(default='uz', max_length=2)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('raw_score', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('iq_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('test_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='testing.testcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.testsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
