# Generated by Django 6.0.5 on 2026-09-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_index',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='language',
            field=models.CharField(default='uz', max_length=2),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
