# Generated by Django 6.1.1 on 2026-10-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_testsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default="Boshqalarga o'xshamagan rasmni toping")),
                ('hint_text', models.CharField(blank=True, max_length=200)),
                ('images', models.JSONField(default=list)),
                ('correct_index', models.PositiveIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Rasm savoli',
                'verbose_name_plural': 'Rasm savollari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
