# Generated by Django 6.1.1 on 2026-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_imagequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagequestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='videos',
            field=models.JSONField(blank=True, default=list, help_text="Video ro'yxati: [{title, url, thumbnail, duration}]"),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('pattern', 'Pattern Recognition'), ('spatial', 'Spatial Visualization'), ('numerical', 'Numerical Sequences'), ('abstract', 'Abstract Reasoning'), ('algebra', 'Algebra'), ('geometry', 'Geometry'), ('arithmetic', 'Arithmetic'), ('logic', 'Logic'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('ortography', 'Ortografiya'), ('literature', 'Adabiyot'), ('grammar_uz', 'Grammatika'), ('analysis', 'Tahlil'), ('grammar_ru', 'Грамматика'), ('vocabulary_ru', 'Лексика'), ('reading_ru', 'Чтение')], max_length=30),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='code',
            field=models.CharField(choices=[('iq', 'IQ Test'), ('math', 'Matematika'), ('english', 'Ingliz tili'), ('native', 'Ona tili va Adabiyot'), ('russian', 'Rus tili')], max_length=20, unique=True),
        ),
    ]
